### ISSUE TITLE
Individual Buffering of Layers

### ISSUE THREAD

**Issue by henrik-wielert** [nefino/roadmap#13]
Individual buffers for each layer can be set inside the Geo app. This feature enables users to get the Geodata according to distance regulations, that defined by the planning authorities. This not only saves time but it also prevents GIS users from possible mistakes during the buffering of relevant layers.

**Comment by chris-stetter** [comment]
This has shipped: https://docs.nefino.li/changelog/individuelles-puffern-von-geodaten.
