### ISSUE TITLE
Analyses: White Area Mapping and Taboo Zones

### ISSUE THREAD

**Issue by henrik-wielert** [nefino/roadmap#14]
Renewable energy projects usually start with the identification of suitable sites. As part of this process, GIS staff conduct a white space analysis to determine taboo zones (areas where no assets may be planned) and then subtract these taboo zones from the analyzed area. This feature now performs these two steps fully automatically and provides the user with the white space and/or taboo zone for the selected exclusion criteria as a result.

**Comment by chris-stetter** [comment]
This as shipped: https://docs.nefino.li/changelog/weiflachenberechnung-und-zusammenstellen-von-tabuzonen 🚀.
