### ISSUE TITLE
Templates for Analyses

### ISSUE THREAD

**Issue by henrik-wielert** [nefino/roadmap#15]
With the help of templates, users can enter the distance regulations in a structured way and apply them to our geodata in Nefino Li Geo. Templates can be created and shared individually as well as rolled out company-wide. On the one hand, this saves a lot of time when compiling the criteria for an analysis. On the other hand, it also avoids possible errors.

**Comment by chris-stetter** [comment]
This has shipped https://docs.nefino.li/changelog/vorlagen-fur-tabu-und-weiflachenanalysen.
