### ISSUE TITLE
Perform analyses at the community level

### ISSUE THREAD

**Issue by henrik-wielert** [nefino/roadmap#16]
This extension allows users of the Geo App to perform their analyses directly for an entire municipality in a fully automated manner according to their own selected restrictions. In addition to an extensive area search, this also makes it possible to show the local authorities directly where potentials are located.

**Comment by chris-stetter** [comment]
This has shipped: https://docs.nefino.li/changelog/gemeinden-als-analysegebiet-wahlbar.
