### ISSUE TITLE
Saving filter settings as favourites

### ISSUE THREAD

**Issue by henning-arends** [nefino/roadmap#2]
With the favourites function, filter settings can be saved in the News App and thus quickly accessed again. In this way, you can always keep an eye on all the news from your relevant investigation areas. The favourite search and filter settings can be assigned an individual favourite name. In the future, it will be possible to share the created favourites in your team.

**Comment by chris-stetter** [comment]
This has shipped: https://docs.nefino.li/changelog/speichern-von-filtereinstellungen-mit-eigenen-favoriten.
