### ISSUE TITLE
Share favourites within the organisation

### ISSUE THREAD

**Issue by henning-arends** [nefino/roadmap#3]
Favourite search and filter settings can be shared within a team. The team members can then also access them and benefit from the settings. Favourites help to receive all messages on the areas relevant to the team even faster and to work more efficiently.

With this update it is possible to:

- Share favourites with the team
- Edit the individual name of the favourites
- Edit shared favourites as admin

**Comment by chris-stetter** [comment]
This has shipped: https://docs.nefino.li/changelog/favoriten-innerhalb-der-organisation-teilen.
