### ISSUE TITLE
New News-Type "Projekte"

### ISSUE THREAD

**Issue by henning-arends** [nefino/roadmap#4]
In addition to the already available news types "Ausschreibung" and "Planung", the new news type "Projekte" is now available. This includes news about planned wind farms and solar parks from project developers, which indicate that a site has already been secured by the respective project developer.

This includes, among other things, news on:

- Development decisions
- Development plans
- Reports on project presentations

**Comment by chris-stetter** [comment]
This has shipped: https://docs.nefino.li/changelog/neuer-newstyp-projekte-ab-sofort-verfugbar.
