### ISSUE TITLE
Integration of "Ratsinformationssysteme"

### ISSUE THREAD

**Issue by henning-arends** [nefino/roadmap#7]
A lot of relevant Information on municipality level is published in the respective "Ratsinformationssystem". Including them in the App adds a huge benefit to all users.

**Comment by chris-stetter** [comment]
This has shipped: https://docs.nefino.li/changelog/ratsinformationssysteme-sind-da-ab-jetzt-auch-bis-zu-30-tage-im-voraus-up-to-date.
